restaurants/urls.py
from django.contrib import admin
from django.urls import path

# from .views import del_restaurant, menu, index, taiwan_rest, new_restaurant, edit_restaurant, del_restaurant, foods
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', views.menu),
    path('index/', views.index),
    path('restaurants/', views.taiwan_rest),
    path('restaurant/new/', views.new_restaurant),
    path('restaurant/<int:r_id>/edit/', views.edit_restaurant),
    path('restaurant/<int:r_id>/del/', views.del_restaurant),
    path('restaurant/<int:r_id>/foods/', views.foods),
    path('restaurant/<int:r_id>/food/new/', views.new_food),
    path('restaurant/<int:r_id>/food/<int:f_id>/edit/', views.edit_food),
    path('restaurant/<int:r_id>/food/<int:f_id>/del/', views.del_food)
]

restaurants/models.py
from django.db import models

class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50)
    # 
    def __str__(self):
        return self.name

class Food(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3, decimal_places=0)
    comment = models.CharField(max_length=50)
    is_spicy = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

restaurants/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Restaurant, Food

def menu(request):
    r = Restaurant.objects.get(id=2)

    return render(request, 'menu.html', locals())

def index(request):
    return render(request, 'index.html')

def taiwan_rest(request):
    restaurants = Restaurant.objects.all()
    return render(request, 'restaurants.html', locals())

def new_restaurant(request):
    if request.method == 'GET':
        return render(request, 'new_restaurant.html')
    else:
        restaurant_name = request.POST['restaurant_name']
        restaurant_phone_number = request.POST['restaurant_phone_number']
        restaurant_address = request.POST['restaurant_address']
        Restaurant.objects.create(name = restaurant_name,
            phone_number = restaurant_phone_number,
            address = restaurant_address)

        return HttpResponseRedirect('/restaurants/')

def edit_restaurant(request, r_id):
    if request.method == 'GET':
        restaurants = Restaurant.objects.filter(id = r_id)
        if (len(restaurants) > 0):
            restaurant = restaurants[0]
            response = render(request, 'edit_restaurant.html', locals())
            response.set_cookie('restaurant_id', r_id)
            return response
        else:
            return HttpResponseRedirect('/restaurants/')
    else:
        restaurants = Restaurant.objects.filter(id = r_id)
        if (len(restaurants) > 0):
            restaurant = restaurants[0]
            restaurant.name = request.POST['restaurant_name']
            restaurant.phone_number = request.POST['restaurant_phone_number']
            restaurant.address = request.POST['restaurant_address']
            restaurant.save()
        return HttpResponseRedirect('/restaurants/')

def del_restaurant(request, r_id):
    Restaurant.objects.filter(id = r_id).delete()
    return HttpResponseRedirect('/restaurants/')

def foods(request, r_id):
    restaurants = Restaurant.objects.filter(id = r_id)
    if (len(restaurants) > 0):
        restaurant = restaurants[0]
        return render(request, 'foods.html', locals())
    else:
        return HttpResponseRedirect('/restaurants')

def new_food(request, r_id):
    if request.method == 'GET':
        restaurant_id = r_id
        return render(request, 'new_food.html', locals())
    else:
        food_name = request.POST['food_name']
        food_price = request.POST['food_price']
        food_comment = request.POST['food_comment']
        food_is_spicy = request.POST['food_is_spicy']
        restaurant = Restaurant.objects.get(id = r_id)
        Food.objects.create(name = food_name,
            price = food_price,
            comment = food_comment,
            is_spicy = food_is_spicy,
            restaurant = restaurant)

        return HttpResponseRedirect(f'/restaurant/{r_id}/foods/')

def edit_food(request, r_id, f_id):
    if request.method == 'GET':
        foods = Food.objects.filter(id = f_id)
        if (len(foods) > 0):
            food = foods[0]
            restaurant_id = r_id
            return render(request, 'edit_food.html', locals())
        else:
            return HttpResponseRedirect(f'/restaurant/{r_id}/foods/')
    else:
        foods = Food.objects.filter(id = f_id)
        if (len(foods) > 0):
            food = foods[0]
            food.name = request.POST['food_name']
            food.price = request.POST['food_price']
            food.comment = request.POST['food_comment']
            food.is_spicy = request.POST['food_is_spicy']
            food.save()
        return HttpResponseRedirect(f'/restaurant/{r_id}/foods/')

def del_food(request, r_id, f_id):
    Food.objects.filter(id = f_id).delete()
    return HttpResponseRedirect(f'/restaurant/{r_id}/foods/')        

templates/edit_food.html
{% extends 'blank.html' %}

{% block content %}
<form method="post" action="/restaurant/{{ restaurant_id }}/food/{{ food.id }}/edit/">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6 text-right">名稱</div>
        <div class="col-md-6"><input type="text" name="food_name" value="{{ food.name }}" required maxlength="20"></div>
        <div class="col-md-6 text-right">價格</div>
        <div class="col-md-6"><input type="number" name="food_price" value="{{ food.price }}" required maxlength="3"></div>
        <div class="col-md-6 text-right">評語</div>
        <div class="col-md-6"><input type="text" name="food_comment" value="{{ food.comment }}" maxlength="50"></div>
        <div class="col-md-6 text-right">辣</div>
        <div class="col-md-6">
            <input type="radio" name="food_is_spicy" value="0" {% if not food.is_spicy %}checked{% endif %}>不會
            <input type="radio" name="food_is_spicy" value="1" {% if food.is_spicy %}checked{% endif %}>會
        </div>
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-primary">儲存</button>
            <button type="reset" class="btn btn-secondary">清空</button>
            <a class="btn btn-secondary" href="/restaurant/{{ restaurant_id }}/foods/">取消</a>
        </div>
    </div>
</form>
{% endblock %}

templates/edit_restaurant.html
{% extends 'blank.html' %}

{% block content %}
<form method="post" action="/restaurant/{{ restaurant.id }}/edit/">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6 text-right">名稱</div>
        <div class="col-md-6"><input type="text" name="restaurant_name" value="{{ restaurant.name }}" required maxlength="20"></div>
        <div class="col-md-6 text-right">電話</div>
        <div class="col-md-6"><input type="text" name="restaurant_phone_number" value="{{ restaurant.phone_number }}" required maxlength="15"></div>
        <div class="col-md-6 text-right">住址</div>
        <div class="col-md-6"><input type="text" name="restaurant_address" value="{{ restaurant.address}}" maxlength="50"></div>
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-primary">儲存</button>
            <button type="reset" class="btn btn-secondary">清空</button>
            <a class="btn btn-secondary" href="/restaurants/">取消</a>
        </div>
    </div>
</form>
{% endblock %}

templates/foods.html
{% extends 'blank.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12 text-right">
        <a class="btn btn-primary" href="/restaurant/{{ restaurant.id }}/food/new">新增</a>
    </div>
</div>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th></th>
            <th>名稱</th>
            <th>價格</th>
            <th>評語</th>
            <th>辣</th>
        </tr>
    </thead>
    <tbody>
        {% for f in restaurant.food_set.all %}
        <tr>
            <td>
                <a href="/restaurant/{{ restaurant.id }}/food/{{ f.id }}/edit/" class="btn btn-primary">編輯</a>
                <a href="/restaurant/{{ restaurant.id }}/food/{{ f.id }}/del/" class="btn btn-danger">刪除</a>
            </td>
            <td>{{ f.name }}</td>
            <td>{{ f.price }}</td>
            <td>{{ f.comment }}</td>
            <td>{% if f.is_spicy %}辣{% else %}不辣{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/index.html
{% extends 'blank.html' %}

{% block content %}
<h1>這是Index頁</h1>
{% endblock %}

templates/menu.html
<!DOCTYPE html>
<html>
    <head>
        <title>菜單</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">        
    </head>
    <body>
        <div class="container">
            <h2>{{ r.name }}</h2>
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>名稱</th>
                        <th>價格</th>
                        <th>說明</th>
                        <th>辣</th>
                    </tr>
                </thead>
                <tbody>
                    {% for food in r.food_set.all %}
                    <tr>
                        <td>{{ food.name }}</td>
                        <td>{{ food.price }}</td>
                        <td>{{ food.comment }}</td>
                        <td>{% if food.is_spicy %}辣{% else %}不辣{% endif %}</td>
                    </tr>
                    {% empty %}
                    <tr colspan="3">
                        <td>本餐廳啥都沒賣！</td>
                    </tr>
                    {% endfor %}                    
                </tbody>
            </table>
        </div>



    </body>
</html>

templates/new_food.html
{% extends 'blank.html' %}

{% block content %}
<form method="post" action="/restaurant/{{ restaurant_id }}/food/new/">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6 text-right">名稱</div>
        <div class="col-md-6"><input type="text" name="food_name" required maxlength="20"></div>
        <div class="col-md-6 text-right">價格</div>
        <div class="col-md-6"><input type="number" name="food_price" required maxlength="3"></div>
        <div class="col-md-6 text-right">評語</div>
        <div class="col-md-6"><input type="text" name="food_comment" maxlength="50"></div>
        <div class="col-md-6 text-right">辣</div>
        <div class="col-md-6">
            <input type="radio" name="food_is_spicy" value="0" checked>不會
            <input type="radio" name="food_is_spicy" value="1">會
        </div>
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-primary">儲存</button>
            <button type="reset" class="btn btn-secondary">清空</button>
            <a class="btn btn-secondary" href="/restaurant/{{ restaurant_id }}/foods/">取消</a>
        </div>
    </div>
</form>
{% endblock %}

templates/new_restaurant.html
{% extends 'blank.html' %}

{% block content %}
<form method="post" action="/restaurant/new/">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6 text-right">名稱</div>
        <div class="col-md-6"><input type="text" name="restaurant_name" required maxlength="20"></div>
        <div class="col-md-6 text-right">電話</div>
        <div class="col-md-6"><input type="text" name="restaurant_phone_number" required maxlength="15"></div>
        <div class="col-md-6 text-right">住址</div>
        <div class="col-md-6"><input type="text" name="restaurant_address" maxlength="50"></div>
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-primary">儲存</button>
            <button type="reset" class="btn btn-secondary">清空</button>
            <a class="btn btn-secondary" href="/restaurants/">取消</a>
        </div>
    </div>
</form>
{% endblock %}

templates/restaurants.html
{% extends 'blank.html' %}

{% block content %}
<div class="row">
    <div class="col-md-12 text-right">
        <a class="btn btn-primary" href="/restaurant/new/">新增</a>
    </div>
</div>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th></th>
            <th>名稱</th>
            <th>電話</th>
            <th>住址</th>
        </tr>
    </thead>
    <tbody>
        {% for r in restaurants %}
        <tr>
            <td>
                <a href="/restaurant/{{ r.id }}/edit/" class="btn btn-primary">編輯</a>
                <a href="/restaurant/{{ r.id }}/del/" class="btn btn-danger">刪除</a>
                <a href="/restaurant/{{ r.id }}/foods" class="btn btn-secondary">菜單</a>
            </td>
            <td>{{ r.name }}</td>
            <td>{{ r.phone_number }}</td>
            <td>{{ r.address }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}